const IMG_PNG: &str =
    "iVBORw0KGgoAAAANSUhEUgAAArwAAAK8CAYAAAANumxDAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAX\
AUlEQVR4nO3dv4ueZb7H8WuOW6xgY7GSKQZWXDAbItHCoE2CjfgXmDRJiDaGCNvlnHabcCTVYk5Q\
lk0IWkT2HxAhxcRCiNUwQgzENSRNtrIJ7DYyp9iIMc7M82PuX9fner3KzF18yw837+fOytbW1lYB\
AIBQ/zX2AQAA0CeDFwCAaAYvAADRDF4AAKIZvAAARDN4AQCIZvACABDN4AUAIJrBCwBANIMXAIBo\
Bi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA0QxeAACiGbwAAEQz\
eAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYvAADRDF4AAKIZvAAARDN4AQCIZvACABDN4AUAIJrB\
CwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA0Qxe\
AACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYvAADRDF4AAKIZvAAARDN4AQCIZvAC\
ABDN4AUAIJrBCwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0gxcA\
gGgGLwAA0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYvAADRDF4AAKIZvAAA\
RDN4AQCIZvACABDN4AUAIJrBCwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3gBQAg\
msELAEA0gxcAgGgGLwAA0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYvAADR\
DF4AAKIZvAAARDN4AQCIZvACABDN4AUAIJrBCwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gBAIhm\
8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsAQDSD\
FwCAaAYvAADRDF4AAKIZvAAARDN4AQCIZvACABDN4AUAIJrBCwBANIMXAIBoBi8AANEMXgAAohm8\
AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAF\
ACCawQsAQDSDF4Dm3Llzp5w6daqsrq6W5557rpw8ebLcvXt37LOAnqxsbW1tjX0EAAzl7t275bXX\
Xitn/vnPX/z7R/v2levXr5cDBw6MdBnQF4MXgKacPHmyvPDJJ9v+7dr+/eXrr78uzzzzzMBXAX2S\
NADQlM8//3zHvx3/9tty5syZ4l0QZDF4AWjKU089tevf//Dpp+XKlSsDXQMMweAFoClvvvnmzGfO\
nj1bNjc3B7gGGIKGF4Cm3L59u7zyyivlv//1r12f0/NCDm94AWjKiy++WC5evDjzOT0v5DB4AWjO\
6dOny3cnTsx8Ts8LGSQNADTp4cOH5dVXXy3Hv/121+f+97e/LTdv3iwvvfTSQJcBXTN4AWjWN998\
Uw4fPqznhXCSBgCadfDgQT0vNMDgBaBpel7IJ2kAoHl6Xshm8AJA0fNCMkkDABQ9LyQzeAHgET0v\
ZJI0AMBj9LyQx+AFgCfoeSGLpAEAnqDnhSwGLwBsQ88LOSQNALADPS9kMHgBYBd6XqifpAEAdqHn\
hfoZvAAwg54X6iZpAIA56HmhXgYvAMxJzwt1kjQAwJz0vFAngxcAFqDnhfpIGgBgQXpeqIvBCwBL\
0PNCPSQNALAEPS/Uw+AFgCXpeaEOkgYA2AM9L0yfwQsAe6TnhWmTNADAHul5YdoMXgDogJ4XpkvS\
AAAd0fPCNBm8ANAhPS9Mj6QBADqk54XpMXgBoGN6XpgWSQMA9EDPC9Nh8AJAT/S8MA2SBgDoiZ4X\
psHgBYAe6XlhfJIGAOiZnhfGZfACwAD0vDAeSQMADEDPC+MxeAFgIHpeGIekAQAGpOeF4Rm8ADAw\
PS8MS9IAAAPT88KwDF4AGIGeF4YjaQCAkeh5YRgGLwCMSM8L/ZM0AMCI9LzQP4MXAEam54V+SRoA\
YAL0vNAfgxcAJkLPC/2QNADAROh5oR8GLwBMiJ4XuidpAICJ0fNCtwxeAJggPS90R9IAABOk54Xu\
GLwAMFF6XuiGpAEAJkzPC3tn8ALAxOl5YW8kDQAwcXpe2BuDFwAqoOeF5UkaAKASel5YjsELABXR\
88LiJA0AUBE9LyzO4AWAyuh5YTGSBgCokJ4X5mfwAkCl9LwwH0kDAFRKzwvzMXgBoGJ6XphN0gAA\
ldPzwu4MXgAIoOeFnUkaACCAnhd2ZvACQAg9L2xP0gAAQfS88GsGLwCE0fPCL0kaACCMnhd+yeAF\
gEB6XviZpAEAQul54T8MXgAIpucFSQMARNPzgsELAPH0vLRO0gAADdDz0jKDFwAaoeelVZIGAGiE\
npdWGbwA0BA9Ly2SNABAY/S8tMbgBYAG6XlpiaQBABqk56UlBi8ANErPSyskDQDQMD0vLTB4AaBx\
el7SSRoAoHF6XtJV/Yb33r175dy5c2V9fb289+DB2OcAUKGP9u0rR48eLRcuXChra2tjnzOara2t\
curUqfLCJ5/MfHbtb38r77zzzgBXQTeqHbz3798vhw4dKn/64YexTwEgwF+efbZsbGw0PXr1vKSq\
dvAeP368/PGzz8Y+A4Agt44dK9euXRv7jFHpeUlUbcO7vr4+9gkAhLlx48bYJ4xOz0uiagcvANAP\
3+clTbWD9+jRo2OfAECYI0eOjH3CJKysrJRLly6Va/v3z3z27NmzZXNzc4CrYHnVNrx+tAZAl/xo\
7df0vKSo9g3v2tpa2djYKLeOHSsfr66OfQ4Alfp4dbXcOnbM2N2GnpcU1b7hBQD65/u8JDB4AYBd\
+T4vtTN4AYCZ9LzUrNqGFwAYjp6Xmhm8AMBcfJ+XWkkaAIC56XmpkcELACxEz0ttJA0AwEL0vNTG\
4AUAFqbnpSaSBgBgKXpeamHwAgBL0/NSA0kDALA0PS81MHgBgD3R8zJ1kgYAYM/0vEyZwQsAdELP\
y1RJGgCATuh5mSqDFwDojJ6XKZI0AACd0vMyNQYvANA5PS9TImkAADqn52VKDF4AoBd6XqZC0gAA\
9EbPyxQYvABAr/S8jE3SAAD0Ss/L2AxeAKB3el7GJGkAAAah52UsBi8AMBg9L2OQNAAAg9HzMgaD\
FwAYlJ6XoUkaAIDB6XkZksELAIxCz8tQJA0AwCj0vAzF4AUARqPnZQiSBgBgVHpe+mbwAgCj0/PS\
J0kDADA6PS99MngBgEnQ89IXSQMAMBl6Xvpg8AIAk6LnpWuSBgBgUvS8dM3gBQAmR89LlyQNAMAk\
6XnpisELAEyWnpcuSBoAgMnS89IFgxcAmDQ9L3slaQAAJk/Py14YvABAFfS8LEvSAABUQc/Lsgxe\
AKAael6WIWkAAKqi52VRBi8AUB09L4uQNAAA1dHzsgiDFwCokp6XeUkaAIBq6XmZh8ELAFRNz8ss\
kgYAoGp6XmYxeAGA6ul52Y2kAQCIoOdlJwYvABBDz8t2JA0AQAw9L9sxeAGAKHpeniRpAADi6Hl5\
nMELAETS8/ITSQMAEEnPy08MXgAglp6XUiQNAEA4PS8GLwAQT8/bNkkDABBPz9s2gxcAaIKet12S\
BgCgGXreNhm8AEBT9LztkTQAAE3R87bH4AUAmqPnbYukAQBokp63HQYvANAsPW8bJA0AQLP0vG0w\
eAGApul580kaAIDm6XmzGbwAAEXPm0zSAABQ9LzJDF4AgEf0vJkkDQAAj9Hz5jF4AQCeoOfNImkA\
AHiCnjeLwQsAsA09bw5JAwDADvS8GQxeAIBd6HnrJ2kAANiFnrd+Bi8AwAx63rpJGgAA5qDnrZfB\
CwAwJz1vnSQNAABz0vPWyeAFAFjAIj3vBx98MMBFzCJpAABY0Lw9759XVsr169fLG2+8MdBlbMfg\
BQBYwrw97ycvvFDu3Lkz0FVsR9IAALCEgwcPlg8//HDmc99///0A17AbgxcAgGgGLwDAEjY3N8v7\
778/87nnn39+gGvYzW/GPgAAoDYPHz4sb7/9dvmff/971+f+vLJSrv/1rwNdxU684QUAWMDW1lY5\
c+bMzC80lFLK+fPnfaFhAnylAQBgAZcvXy7333135nPfnThRrl69WlZWVga4it0YvAAAc9rc3CyH\
Dx+emTL4r4WnxeAFAJjDvP/ZxAdPP11u3rxZDh48ONBlzKLhBQCYYZFu9+LFi8buxBi8AAAzXLly\
pfzh009nPvfdiRPl9OnTA1zEIiQNAAC70O3Wz+AFANiBbjeDpAEAYBu63RwGLwDANnS7OSQNAABP\
0O1mMXgBAB6j280jaQAAeES3m8ngBQB4RLebSdIAAFB0u8kMXgCgebrdbJIGAKBput18Bi8A0DTd\
bj5JAwDQLN1uGwxeAKBJut12SBoAgObodtti8AIAzdHttkXSAAA0RbfbHoMXAGiGbrdNkgYAoAm6\
3XYZvABAE3S77ZI0AADxdLttM3gBgGi6XSQNAEAs3S6lGLwAQDDdLqVIGgCAULpdfmLwAgBxdLs8\
TtIAAETR7fIkgxcAiKLb5UmSBgAghm6X7Ri8AEAE3S47kTQAANXT7bIbgxcAqJ5ul91IGgCAqul2\
mcXgBQCqpdtlHpIGAKBKul3mZfACAFXS7TIvSQMAUB3dLosweAGAquh2WZSkAQCohm6XZRi8AEA1\
dLssQ9IAAFRBt8uyDF4AYPJ0u+yFpAEAmDTdLntl8AIAk6bbZa8kDQDAZOl26YLBCwBMkm6Xrkga\
AIDJ0e3SJYMXAJgc3S5dkjQAAJOi26VrBi8AMBm6XfogaQAAJkG3S18MXgBgEnS79EXSAACMTrdL\
nwxeAGBUul36JmkAAEaj22UIBi8AMBrdLkOQNAAAo9DtMhSDFwAYnG6XIUkaAIBB6XYZmsELAAxK\
t8vQJA0AwGB0u4zB4AUABqHbZSySBgCgd7pdxmTwAgC90+0yJkkDANAr3S5jM3gBgN7odpkCSQMA\
0AvdLlNh8AIAvdDtMhWSBgCgc7pdpsTgBQA6pdtlaiQNAEBndLtMkcELAHRGt8sUSRoAgE7odpkq\
gxcA2DPdLlMmaQAA9kS3y9QZvADAnuh2mTpJAwCwNN0uNTB4AYCl6HaphaQBAFiYbpeaGLwAwMJ0\
u9RE0gAALES3S20MXgBgbrpdaiRpAADmotulVgYvADAX3S61kjQAADPpdqmZwQsA7Eq3S+0kDQDA\
jnS7JKj6De+9e/fKuXPnyvr6ennvwYOxzwGgQh/t21eOHj1aLly4UNbW1sY+Z3IuX75c7r/77szn\
vjtxoly9erWsrKwMcBUsptrBe//+/XLo0KHypx9+GPsUAAL85dlny8bGhtH7GN0uKaodvMePHy9/\
/Oyzsc8AIMitY8fKtWvXxj5jEnS7JKm24V1fXx/7BADC3LhxY+wTJkG3S5pqBy8A0A/f2yVNtYP3\
6NGjY58AQJgjR46MfcLoNjc3y9mzZ2c+d23//nLp0iU/UqMK1Ta8frQGQJf8aE23S65q3/Cura2V\
jY2NcuvYsfLx6urY5wBQqY9XV8utY8eaH7u6XZJV+4YXAOiO7+2SzOAFgMb53i7pDF4AaJhulxZU\
2/ACAHuj26UVBi8ANMr3dmmFpAEAGqTbpSUGLwA0RrdLayQNANAQ3S4tMngBoCG6XVokaQCARuh2\
aZXBCwAN0O3SMkkDAITT7dI6gxcAwul2aZ2kAQCC6XbB4AWAWLpd+A9JAwAE0u3CzwxeAAik24Wf\
SRoAIIxuF37J4AWAILpd+DVJAwCE0O3C9gxeAAih24XtSRoAIIBuF3Zm8AJA5XS7sDtJAwBUTLcL\
sxm8AFAx3S7MJmkAgErpdmE+Bi8AVEi3C/OTNABAZXS7sBiDFwAqo9uFxUgaAKAiul1YnMELAJXQ\
7cJyJA0AUAHdLizP4AWACuh2YXmSBgCYON0u7I3BCwATptuFvZM0AMBE6XahGwYvAEyUbhe6IWkA\
gAnS7UJ3DF4AmBjdLnRL0gAAE6Lbhe4ZvAAwIbpd6J6kAQAmQrcL/TB4AWACdLvQH0kDAIxMtwv9\
MngBYGS6XeiXpAEARqTbhf4ZvAAwEt0uDEPSAAAj0O3CcAxeABiBbheGI2kAgIHpdmFYBi8ADEi3\
C8OTNADAQHS7MA6DFwAGotuFcUgaAGAAul0Yj8ELAD3T7cK4JA0A0CPdLozP4AWAHul2YXySBgDo\
iW4XpsHgBYAe6HZhOiQNANAx3S5Mi8ELAB3T7cK0SBoAoEO6XZgegxcAOqLbhWmSNABAB3S7MF0G\
LwB0QLcL0yVpAIA90u3CtBm8ALAHul2YPkkDACxJtwt1MHgBYEm6XaiDpAEAlqDbhXoYvACwIN0u\
1EXSAAAL0O1CfQxeAFiAbhfqI2kAgDnpdqFOBi8AzEG3C/WSNADADLpdqJvBCwAz6HahbpIGANiF\
bhfqZ/ACwA50u5BB0gAA29DtQg6DFwC2oduFHJIGAHiCbheyGLwA8BjdLuSRNADAI7pdyGTwAsAj\
ul3IJGkAgKLbhWQGLwDN0+1CNkkDAE3T7UI+gxeApul2IZ+kAYBm6XahDQYvAE3S7UI7JA0ANEe3\
C20xeAFojm4X2iJpAKApt2/fLi+//LJuFxrym7EPAIAhnT9/fubY/eDpp8vNv//d2IUQkgYAmvLF\
F1/MfEa3C1kMXgCa8uOPP+76d90u5DF4AWjKW2+9tePfru3fXy5dulRWVlYGvAjomx+tAdCUu3fv\
ltdff7289+DBL/79o337yvXr18uBAwdGugzoize8ADTl97//ffnyyy/L96dOlY9XV8v//e535R8n\
T5avvvrK2IVQ3vACABDNG14AAKIZvAAARDN4AQCIZvACABDN4AUAIJrBCwBANIMXAIBoBi8AANEM\
XgAAohm8AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA0QxeAACiGbwAAEQzeAEAiGbw\
AgAQzeAFACCawQsAQDSDFwCAaAYvAADRDF4AAKIZvAAARDN4AQCIZvACABDN4AUAIJrBCwBANIMX\
AIBoBi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA0QxeAACiGbwA\
AEQzeAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYvAADRDF4AAKIZvAAARDN4AQCIZvACABDN4AUA\
IJrBCwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA\
0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYvAADRDF4AAKIZvAAARDN4AQCI\
ZvACABDN4AUAIJrBCwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3gBQAgmsELAEA0\
gxcAgGgGLwAA0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYvAADRDF4AAKIZ\
vAAARDN4AQCIZvACABDN4AUAIJrBCwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gBAIhm8AIAEM3g\
BQAgmsELAEA0gxcAgGgGLwAA0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsAQDSDFwCAaAYv\
AADRDF4AAKIZvAAARDN4AQCIZvACABDN4AUAIJrBCwBANIMXAIBoBi8AANEMXgAAohm8AABEM3gB\
AIhm8AIAEM3gBQAgmsELAEA0gxcAgGgGLwAA0QxeAACiGbwAAEQzeAEAiGbwAgAQzeAFACCawQsA\
QDSDFwCAaAYvAADRDF4AAKL9P4eKb2AYQ1GJAAAAAElFTkSuQmCC";

const IMG_JPG: &str =
    "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAFA3PEY8MlBGQUZaVVBfeMiCeG5uePWvuZHI////////\
////////////////////////////////////////////2wBDAVVaWnhpeOuCguv/////////////\
////////////////////////////////////////////////////////////wAARCAK8ArwDASIA\
AhEBAxEB/8QAGQABAAMBAQAAAAAAAAAAAAAAAAMEBQIB/8QAKBABAAEEAQMEAgMBAQAAAAAAAAEC\
AxShUhEhMQQSEzJBUSIjgWHx/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGxEBAQEBAQEBAQAA\
AAAAAAAAAAEREjEhQQL/2gAMAwEAAhEDEQA/ALoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAOa6oopmqrxAOL92LVH7qnxCD09+uu77ap6xP/ADwguXJuVzVK36Wz\
8dPuqj+U6RrMiwArIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAADxR9Te+SrpH1jaX1d7p/XTPefKvYtTdr6fiPMo1J+1L6Wz7p+SqO0e\
F15ERTERHaIeqlugAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAiv3fio7fafDuuqKKZqq8Qzrlc3K5qkWTXkRVcr6R3qmWhatxboimP9\
n9o/TWfjp91UfynSwi26AKyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAPHqr6u90/rpnvPkJNQ+pvfJV0j6xt36Wz7p+SqO0eEVi1N2vp\
+I8y0YiKYiI7RCN258egKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAA5rqiimaqvEA4v3fio7fafChEVXK+kd6pl7crm5XNUrfprPx0+\
6r7TpPW/IktW4tURTH+z+0gKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8UfU3vkq6R9Y2l9Xe6f10z3nyr2LU3a+n4jzKNSftS+ls\
+6fkqjtHhdeREUxER2iHqpboAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIr934qO32nw7rqiimaqvEM65XNyuapFk15EVXK+kd6ploW\
rcW6Ipj/AGf2j9NZ+On3VR/KdLCLboArIAAADyZiImZ7RCLJs89S6vUTctVUxPSZUsa9w3Ask/Vv\
Js89SZNnnqVTGvcNwY17huEayLeTZ56kybPPUqmNe4bgxr3DcBkW8mzz1Jk2eepVMa9w3BjXuG4D\
It5NnnqTJs89SqY17huDGvcNwGRbybPPUmTZ56lUxr3DcGNe4bgMi3k2eepMmzz1KpjXuG4Ma9w3\
AZFvJs89SZNnnqVTGvcNwY17huAyLeTZ56kybPPUqmNe4bgxr3DcBkW8mzz1Jk2eepVMa9w3BjXu\
G4DIt5NnnqTJs89SqY17huDGvcNwGRbybPPUmTZ56lUxr3DcGNe4bgMi3k2eepMmzz1KpjXuG4Ma\
9w3AZFvJs89SZNnnqVTGvcNwY17huAyLeTZ56kybPPUqmNe4bgxr3DcBkW8mzz1Jk2eepVMa9w3B\
jXuG4DIt5NnnqTJs89SqY17huDGvcNwGRbybPPUmTZ56lUxr3DcGNe4bgMi3k2eepMmzz1KpjXuG\
4Ma9w3AZFvJs89SZNnnqVTGvcNwY17huAyLeTZ56kybPPUqmNe4bgxr3DcBkW8mzz1Jk2eepVMa9\
w3BjXuG4DIt5NnnqTJs89SqY17huDGvcNwGRbybPPUmTZ56lUxr3DcGNe4bgMi3k2eepMmzz1Kpj\
XuG4Ma9w3AZFvJs89S6ou0XJmKausqWNe4bhL6exXTc91UdIj/vkSyLgCsgAAAAAAAAAAAAAAAAA\
AAAADx6q+rvdP66Z7z5CTUPqb3yVdI+sbd+ls+6fkqjtHhFYtTdr6fiPMtGIimIiO0QjdufHoCsA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAOa6oopmqrxAOL934qO32nwoRFVyvpHeqZe3K5uVzVK36az8dPuq+06T1vyJLVuLVEUx/s/tI\
CsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAPFH1N75KukfWNpfV3un9dM958q9i1N2vp+I8yjUn7UvpbPun5Ko7R4XXkRFMREdoh6qW\
6ACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAACK/d+Kjt9p8O66oopmqrxDOuVzcrmqRZNeRFVyvpHeqZaFq3FuiKY/wBn9o/TWfjp91Uf\
ynSwi26AKyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAPHqr6u90/rpnvPkJNQ+pvfJV0j6xt36Wz7p+SqO0eEVi1N2vp+I8y0YiKYiI7R\
CN258egKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAiv3YtUdvtPhQiKrlfSO9UyXLk3K5qq/8AFv0luKaPf2mZ0jfkS2rcWqIpj/Z/\
aQFYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAUvVWfbPyUx2nz/xx6a98dXSfrOl+YiqJie8Szr9qbVfT8T4lG5d+NF6q+kvdf66p\
7x4WlYswAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAR3bcXaJpn/J/SQBlzFVuvpPaqJX7F35aO/2jy49TZ+Sn3U/aNqluubdcVQnj\
fsaY5oqiumKqfEulYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAFL1Vn2z8lMdp8rryYiYmJ7xIsuKPpr3x1dJ+s6XmdftTar6fifE\
rHpL3X+uqe8eEWz9i0ArIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAACO7bi5RNM/5P6Z8xVbr6T2qiWor+ps/JT7qY/lG0alx3Yu/L\
R3+0eUrMt1zbriqGjRVFdMVU+JVLMdACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKXqrPtn5KY7T5cemvfHV0n6zpfmIqiYnvEs6\
/am1X0/E+JRuXfjReqvpL3X+uqe8eFpWLMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEd23F2iaZ/yf0kAZcxVbr6T2qiV+xd+Wjv\
9o8uPU2fkp91P2japbrm3XFUJ437GmOaKorpiqnxLpWAAAAAAAeTMREzPaIRZNrnqQTCHJs89SZN\
nnqRcqYQ5NnnqTJs89SGVMIcmzz1Jk2eepDKmEOTZ56kybPPUhlTCHJs89SZNnnqQyphDk2eepMm\
zz1IZUwhybPPUmTZ56kMqYQ5NnnqTJs89SGVMIcmzz1Jk2eepDKmEOTZ56kybPPUhlTCHJs89SZN\
nnqQyphDk2eepMmzz1IZUwhybPPUmTZ56kMqYQ5NnnqTJs89SGVMIcmzz1Jk2eepDKmEOTZ56kyb\
PPUhlTCHJs89SZNnnqQyphDk2eepMmzz1IZUwhybPPUmTZ56kMqYQ5NnnqTJs89SGVMIcmzz1Jk2\
eepDKmEOTZ56kybPPUhlTCHJs89SZNnnqQyphDk2eepMmzz1IZUwhybPPUuqLtFyelFXWRMSAAAA\
AAAAAAAAAAAAAAAAAAAAAAKXqrPtn5KY7T5XXkxExMT3iRZcUfTXvjq6T9Z0vM6/am1X0/E+JWPS\
Xuv9dU948Itn7FoBWQAAAEd6iblqqmJ6TKljXuG4aILLjOxr3DcGNe4bhoiYvVZ2Ne4bgxr3DcNE\
MOqzsa9w3BjXuG4aIYdVnY17huDGvcNw0Qw6rOxr3DcGNe4bhohh1WdjXuG4Ma9w3DRDDqs7GvcN\
wY17huGiGHVZ2Ne4bgxr3DcNEMOqzsa9w3BjXuG4aIYdVnY17huDGvcNw0Qw6rOxr3DcGNe4bhoh\
h1WdjXuG4Ma9w3DRDDqs7GvcNwY17huGiGHVZ2Ne4bgxr3DcNEMOqzsa9w3BjXuG4aIYdVnY17hu\
DGvcNw0Qw6rOxr3DcGNe4bhohh1WdjXuG4Ma9w3DRDDqs7GvcNwY17huGiGHVZ2Ne4bgxr3DcNEM\
Oqzsa9w3BjXuG4aIYdVnY17huDGvcNw0Qw6rOxr3DcGNe4bhohh1WdjXuG4Ma9w3DRDDqs7GvcNw\
l9PYrpue6qOkR/3yuBhf6tAFZAAAAAAAAAAAAAAAAAAAAAAAAAAR3bcXKJpn/J/TPmKrdfSe1US1\
Ff1Nn5KfdTH8o2jUuO7F35aO/wBo8pWZbrm3XFUNGiqK6Yqp8SqWY6AEAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUvVWfbPyUx2n\
y49Ne+OrpP1nS/MRVExPeJZ1+1Nqvp+J8Sjcu/Gi9VfSXuv9dU948LSsWYAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI7tuLtE0z/\
AJP6SAMuYqt19J7VRK/Yu/LR3+0eXHqbPyU+6n7RtUt1zbriqE8b9jTHNFUV0xVT4l0rAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
Apeqs+2fkpjtPldeTETExPeJFlxR9Ne+OrpP1nS8zr9qbVfT8T4lY9Je6/11T3jwi2fsWgFZAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAR3bcXKJpn/J/TPmKrdfSe1US1Ff1Nn5KfdTH8o2jUuO7F35aO/2jylZluubdcVQ0aKorpiqn\
xKpZjoAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAABS9VZ9s/JTHafLz0lcxc9n4qXZiJjpMdYlxRaotzM009JlF35iQBUAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAf/2Q==";

use scuffcommander_core::{
    Base64Image, ButtonData, ButtonStyle, UIButton, UIConfig, UIPage, UIStyle,
};
use std::collections::HashMap;

fn style() -> UIStyle {
    UIStyle {
        default_button_style: ButtonStyle {
            width: "2.5cm".to_string(),
            height: "2.5cm".to_string(),
            bg_color: "#2F4F4F".to_string(),
            fg_color: "#F0FFFF".to_string(),
        },
        bg_color: "#000000".to_string(),
        fg_color: "#FFFFFF".to_string(),
    }
}

fn page_home() -> UIPage {
    let button1 = UIButton::OpenPage(ButtonData {
        target_id: "Complex Actions".to_string(),
        style_override: None,
        img: Some(Base64Image {
            format: "image/png".to_string(),
            data: IMG_PNG.to_string(),
        }),
    });

    let button2 = UIButton::ExecuteAction(ButtonData {
        target_id: "Waiting Scene".to_string(),
        style_override: None,
        img: None,
    });

    let button3 = UIButton::ExecuteAction(ButtonData {
        target_id: "Desktop+VTS Scene".to_string(),
        style_override: None,
        img: None,
    });

    let button4 = UIButton::ExecuteAction(ButtonData {
        target_id: "Qt Expr Toggle".to_string(),
        style_override: Some(ButtonStyle {
            width: "3cm".to_string(),
            height: "2.5cm".to_string(),
            bg_color: "#191970".to_string(),
            fg_color: "#FFFFFF".to_string(),
        }),
        img: None,
    });

    let button5 = UIButton::ExecuteAction(ButtonData {
        target_id: "expressiong Toggle".to_string(),
        style_override: Some(ButtonStyle {
            width: "3cm".to_string(),
            height: "2.5cm".to_string(),
            bg_color: "#191970".to_string(),
            fg_color: "#FFFFFF".to_string(),
        }),
        img: None,
    });

    UIPage {
        buttons: vec![button1, button2, button3, button4, button5],
    }
}

fn page_2() -> UIPage {
    let button1 = UIButton::ExecuteAction(ButtonData {
        target_id: "Dual Expr Toggle".to_string(),
        style_override: None,
        img: None,
    });

    let button2 = UIButton::ExecuteAction(ButtonData {
        target_id: "Scene Toggle".to_string(),
        style_override: None,
        img: None,
    });

    let button3 = UIButton::ExecuteAction(ButtonData {
        target_id: "Model Toggle".to_string(),
        style_override: Some(ButtonStyle {
            width: "2in".to_string(),
            height: "2in".to_string(),
            bg_color: "#191970".to_string(),
            fg_color: "#FFFFFF".to_string(),
        }),
        img: None,
    });

    let button4 = UIButton::ExecuteAction(ButtonData {
        target_id: "Model Dep Expr Toggle".to_string(),
        style_override: Some(ButtonStyle {
            width: "2in".to_string(),
            height: "2in".to_string(),
            bg_color: "#191970".to_string(),
            fg_color: "#FFFFFF".to_string(),
        }),
        img: None,
    });

    let button5 = UIButton::OpenPage(ButtonData {
        target_id: "home".to_string(),
        style_override: None,
        img: Some(Base64Image {
            format: "image/jpg".to_string(),
            data: IMG_JPG.to_string(),
        }),
    });

    UIPage {
        buttons: vec![button1, button2, button3, button4, button5],
    }
}

fn main() {
    let mut pages = HashMap::new();

    pages.insert("home".to_string(), page_home());
    pages.insert("Complex Actions".to_string(), page_2());

    println!(
        "{}",
        serde_json::to_string_pretty(&UIConfig {
            pages,
            style: style()
        })
        .unwrap()
    );
}
